cases hab with u hu,
cases hba with v hv,

rw hu at hv,
rw add_assoc at hv,
symmetry at hv,
have h := eq_zero_of_add_right_eq_self hv,
have u_zero := add_right_eq_zero h,
rw u_zero at hu,
rw add_zero at hu,
symmetry,
exact hu,