rw two_eq_succ_one,
rw one_eq_succ_zero,
repeat {rw pow_succ},
repeat{rw pow_zero},
repeat{rw one_mul},
rw mul_add,
repeat{rw add_mul},
rw succ_mul,
rw ← one_eq_succ_zero,
rw one_mul,
rw add_mul,
simp,
